### ISSUE TITLE
Conflicting documentation at crates.io?

### ISSUE THREAD

**Issue by christopinka** [lukesneeringer/unix-ts#12]
Docs say

```
Add the unix-ts crate to your Cargo.toml file like usual:

[dependencies]
unix-ts = "0.2"
You can create a timestamp with the ts! macro, which takes the Unix timestamp as an argument:

use unix_ts_macros::ts;

```

cargo says

```
Or add the following line to your Cargo.toml:


unix-ts-macros = "0.4.0"


```

**Comment by christopinka** [comment]
New to rust and cargo.

I have

cargo.toml

[dev-dependencies]
unix-ts = "0.4.1"


and 


```rust
#[cfg(test)]
mod tests {
    use super::*;
    use unix_ts_macros::ts;

    #[test]
    fn test_schedule_start_date() {
        let t = ts!(1335020400);
        // let t2 = ts!(1335020400.25);
        assert_eq!(schedule_start_date(t), 1);
    }
}
```

getting

error[E0432]: unresolved import `unix_ts_macros`
   --> apps/cvr/src/scheduler.rs:550:9
    |
550 |     use unix_ts_macros::ts;
    |         ^^^^^^^^^^^^^^ use of undeclared crate or module `unix_ts_macros`

**Comment by lukesneeringer** [comment]
Sorry for not noticing this.

Dependencies in Rust aren't transitive, and `unix_ts` exposes the `ts` macro itself. So it's `use unix_ts::ts;`
